In [13]:
import galois
import numpy as np
from numpy.linalg import *

In [43]:
GF = galois.GF(2,1)
print(GF)

<class 'galois.GF(2)'>


In [46]:
x = GF(1)
print(x + x)

0


In [47]:
C_1= GF(np.matrix ([[1,0,0],[0,1,0], [0,0,0]]))
print(C_1)

[[1 0 0]
 [0 1 0]
 [0 0 0]]


In [48]:
rk_C_1 = matrix_rank(C_1)

In [49]:
rk_C_1

2

In [50]:
def red_mat(C,w):
    C_t = C.copy()
    C_t[:,w:] = 0
    return C_t

In [51]:
red_mat(C_1,1)

GF([[1, 0, 0],
    [0, 0, 0],
    [0, 0, 0]], order=2)

In [58]:
A = GF.Random((3,5))
A

GF([[1, 0, 1, 0, 1],
    [0, 0, 1, 1, 0],
    [0, 1, 0, 0, 0]], order=2)

In [59]:
rk_A = matrix_rank(A)
rk_A_t = matrix_rank(red_mat(A,2))
rk_A,rk_A_t

(3, 2)

In [65]:
p = {"w":2,"dim":(3,5)}

In [69]:
def expe(p):
    A = GF.Random(p["dim"])
    rk_A = matrix_rank(A)
    rk_A_t = matrix_rank(red_mat(A,p["w"]))
    return((rk_A,rk_A_t),(A))

In [71]:
res = dict()
for i in range(100):
    (x,data) = expe(p)
    if x not in res:
        res[x] = data 
p,res


({'w': 2, 'dim': (3, 5)},
 {(3, 2): GF([[0, 1, 0, 1, 0],
      [1, 1, 1, 1, 1],
      [1, 0, 1, 0, 0]], order=2),
  (3,
   1): GF([[0, 0, 1, 1, 1],
      [1, 0, 0, 0, 0],
      [1, 0, 1, 0, 0]], order=2),
  (2,
   2): GF([[1, 0, 0, 1, 1],
      [1, 0, 0, 1, 1],
      [1, 1, 1, 1, 1]], order=2),
  (2,
   1): GF([[1, 0, 0, 0, 0],
      [1, 0, 0, 0, 0],
      [1, 0, 0, 0, 1]], order=2),
  (1,
   1): GF([[1, 0, 0, 0, 1],
      [1, 0, 0, 0, 1],
      [1, 0, 0, 0, 1]], order=2),
  (3,
   0): GF([[0, 0, 0, 1, 0],
      [0, 0, 1, 0, 1],
      [0, 0, 1, 1, 0]], order=2)})