In [1]:
import galois
import numpy as np
from numpy.linalg import *
from tqdm import tqdm

In [2]:
GF = galois.GF(2,1)
print(GF)

<class 'galois.GF(2)'>


In [3]:
x = GF(1)
print(x + x)

0


In [4]:
C_1= GF(np.matrix ([[1,0,0],[0,1,0], [0,0,0]]))
print(C_1)

[[1 0 0]
 [0 1 0]
 [0 0 0]]


In [5]:
rk_C_1 = matrix_rank(C_1)

In [6]:
rk_C_1

2

In [7]:
def red_mat(C,w):
    C_t = C.copy()
    C_t[:,w:] = 0
    return C_t

In [8]:
red_mat(C_1,1)

GF([[1, 0, 0],
    [0, 0, 0],
    [0, 0, 0]], order=2)

In [9]:
A = GF.Random((3,5))
A

GF([[1, 1, 1, 0, 1],
    [0, 1, 0, 1, 0],
    [0, 0, 0, 1, 1]], order=2)

In [10]:
rk_A = matrix_rank(A)
rk_A_t = matrix_rank(red_mat(A,3))
rk_A,rk_A_t

(3, 2)

In [71]:
p = {"w":4,"dim":(6,7)}

In [72]:
def expe(p):
    A = GF.Random(p["dim"])
    rk_A = matrix_rank(A)
    rk_A_t = matrix_rank(red_mat(A,p["w"]))
    return((rk_A,rk_A_t),(A))

In [73]:
res = dict()
for i in tqdm(range(300)):
    (x,data) = expe(p)
    if x not in res:
        res[x] = data 
p,res


  0%|          | 0/300 [00:00<?, ?it/s]

100%|██████████| 300/300 [00:01<00:00, 252.26it/s]


({'w': 4, 'dim': (6, 7)},
 {(6, 4): GF([[1, 0, 1, 1, 0, 0, 0],
      [0, 1, 0, 1, 0, 1, 0],
      [1, 0, 0, 0, 1, 1, 1],
      [0, 0, 1, 0, 0, 0, 0],
      [1, 1, 0, 1, 0, 0, 1],
      [1, 1, 0, 1, 1, 1, 0]], order=2),
  (5,
   4): GF([[0, 1, 0, 0, 0, 1, 1],
      [0, 1, 1, 0, 0, 0, 1],
      [0, 0, 1, 1, 1, 0, 1],
      [0, 1, 1, 0, 1, 1, 1],
      [0, 1, 1, 1, 1, 1, 0],
      [1, 0, 1, 1, 1, 1, 1]], order=2),
  (5,
   3): GF([[1, 1, 1, 0, 0, 1, 0],
      [0, 1, 0, 1, 1, 1, 1],
      [0, 1, 1, 0, 1, 1, 1],
      [1, 1, 0, 1, 1, 0, 0],
      [0, 1, 0, 1, 0, 1, 1],
      [1, 1, 0, 1, 1, 0, 0]], order=2),
  (4,
   3): GF([[1, 1, 1, 1, 1, 1, 0],
      [0, 1, 1, 1, 0, 0, 0],
      [1, 1, 1, 1, 1, 1, 0],
      [1, 1, 1, 1, 0, 1, 0],
      [0, 0, 1, 1, 0, 0, 0],
      [0, 1, 1, 1, 1, 0, 0]], order=2),
  (6,
   3): GF([[0, 0, 1, 1, 1, 1, 0],
      [1, 0, 1, 1, 0, 1, 1],
      [1, 0, 0, 0, 1, 1, 0],
      [1, 0, 0, 0, 0, 1, 0],
      [1, 0, 0, 1, 0, 1, 1],
      [1, 0, 0, 1, 0, 0, 1]], order=2