In [75]:
#import Pkg 

In [76]:
#Pkg.add("CairoMakie")

In [77]:
#mkpath("Plots")


In [20]:
using CairoMakie

In [1]:
using AbstractAlgebra, Random
using AbstractAlgebra: lift
b=2
F = GF(b)
m = 5
s = 2
ρ = m 
t = m - ρ 
N = b^m

32

In [2]:
S = matrix_space(F, m, m)

Matrix space of 5 rows and 5 columns
  over finite field F_2

Point generation digital and reduced digital nets

In [3]:
badic = collect(Iterators.product(fill(0:b-1, m)...))[:]

32-element Vector{NTuple{5, Int64}}:
 (0, 0, 0, 0, 0)
 (1, 0, 0, 0, 0)
 (0, 1, 0, 0, 0)
 (1, 1, 0, 0, 0)
 (0, 0, 1, 0, 0)
 (1, 0, 1, 0, 0)
 (0, 1, 1, 0, 0)
 (1, 1, 1, 0, 0)
 (0, 0, 0, 1, 0)
 (1, 0, 0, 1, 0)
 ⋮
 (1, 1, 1, 0, 1)
 (0, 0, 0, 1, 1)
 (1, 0, 0, 1, 1)
 (0, 1, 0, 1, 1)
 (1, 1, 0, 1, 1)
 (0, 0, 1, 1, 1)
 (1, 0, 1, 1, 1)
 (0, 1, 1, 1, 1)
 (1, 1, 1, 1, 1)

In [4]:
function norm_coord(v,b)
    v_1 = 0.0
    bf = float(b)
    for i in eachindex(v)
        v_1 += v[i] * bf^(-i)
    end
    return v_1
end


norm_coord (generic function with 1 method)

In [5]:
using Test
@test norm_coord([1 1 0 1],2) == 13/16

Test Passed

In [6]:
# norm_coord( AbstractAlgebra.lift.( C_2*collect(badic[4]) ),2)  # you need to convert Tuples to vectors matrix mult...
# C_r2*collect(badic[4])

# If you compute in a finite field, you need to apply the map from Fq to R to make this computation
# work. This map is called 'lift'. So, you need to apply lift to the vector you want to compute with.

In [7]:
function point_gen(C,n,b)
    v = [norm_coord(AbstractAlgebra.lift.(c*n),b) for c in C]   
    return v

end

point_gen (generic function with 1 method)

In [29]:
#  Use Ctrl+/ to comment out and back
if m == 2
    C_1 = [1 0; 0 1]
    C_2 = [0 1; 1 0]
    C_up = [1 1; 1 0]
elseif m == 3

    C_1 = [1 0 0; 0 1 0; 0 0 1]
    C_2 = [0 0 1; 0 1 0; 1 0 0]
    C_up = [1 1 1; 1 1 0; 1 0 0]
    #C_up = [0 0 1; 1 1 0; 1 0 1] # Observation/conj: all (0,3,2) nets have the same nrt_wts  

elseif m == 4 
    C_1 = [1 0 0 0; 0 1 0 0; 0 0 1 0; 0 0 0 1]
    C_2 = [0 0 0 1; 0 0 1 0; 0 1 0 0; 1 0 0 0]
    C_up = [1 1 1 1; 1 1 1 0; 1 1 0 0; 1 0 0 0]

elseif m == 5 
    C_1 = [1 0 0 0 0; 0 1 0 0 0; 0 0 1 0 0; 0 0 0 1 0; 0 0 0 0 1]
    # C_2 = [0 0 0 0 1; 0 0 0 1 0; 0 0 1 0 0; 0 1 0 0 0; 1 0 0 0 0]
    C_up = [1 1 1 1 1; 1 1 1 1 0; 1 1 1 0 0; 1 1 0 0 0; 1 0 0 0 0]
    C_2 = [0 1 0 1 1; 0 1 1 0 1; 1 0 1 1 1; 0 1 1 1 1; 1 1 0 0 0]
end
    
C_1, C_2, C_up  = S(C_1), S(C_2), S(C_up)
C = [C_1,C_2] 

2-element Vector{AbstractAlgebra.Generic.MatSpaceElem{AbstractAlgebra.GFElem{Int64}}}:
 [1 0 0 0 0; 0 1 0 0 0; 0 0 1 0 0; 0 0 0 1 0; 0 0 0 0 1]
 [0 1 0 1 1; 0 1 1 0 1; 1 0 1 1 1; 0 1 1 1 1; 1 1 0 0 0]

In [30]:
C_LP = [C_1, C_up]

2-element Vector{AbstractAlgebra.Generic.MatSpaceElem{AbstractAlgebra.GFElem{Int64}}}:
 [1 0 0 0 0; 0 1 0 0 0; 0 0 1 0 0; 0 0 0 1 0; 0 0 0 0 1]
 [1 1 1 1 1; 1 1 1 1 0; 1 1 1 0 0; 1 1 0 0 0; 1 0 0 0 0]

In [36]:
collect(C_2)

5×5 Matrix{AbstractAlgebra.GFElem{Int64}}:
 0  1  0  1  1
 0  1  1  0  1
 1  0  1  1  1
 0  1  1  1  1
 1  1  0  0  0

In [37]:
det(C_2)

0

In [44]:
K = [0 1 0 1 1; 0 1 1 0 1; 1 0 1 1 1; 0 1 1 1 1; 1 1 0 0 0]

5×5 Matrix{Int64}:
 0  1  0  1  1
 0  1  1  0  1
 1  0  1  1  1
 0  1  1  1  1
 1  1  0  0  0

In [45]:
det(K)

-1.9999999999999996

In [137]:
# m = 5 Use Ctrl+/ to comment out
# C_1 = [1 1 1 1 1; 0 1 0 1 0; 0 0 1 1 0; 0 0 0 1 0; 0 0 0 0 1]
# C_2 = [1 0 0 0 0; 0 1 0 0 0; 0 0 1 0 0; 0 0 0 1 0; 0 0 0 0 1]
# C_1, C_2  = S(C_1), S(C_2) 
# C = [C_1,C_2]

In [138]:
#point_gen(C,collect(badic[8]),3)

In [139]:
#K_1 = (inv(C_1)*(C_1))

In [14]:
function gen_all_points(C,b)
    badic = collect(Iterators.product(fill(0:b-1, m)...))[:]
    pts = [point_gen(C,collect(n),b) for n in badic]
    return pts
end

gen_all_points (generic function with 1 method)

In [15]:
gen_all_points(C,b)
pts = gen_all_points(C,b)
#pts = sort(gen_all_points(C,b))
#pts_shift = [pts[i] .+ 0.02 for i in 1:length(pts)]


32-element Vector{Vector{BigFloat}}:
 [0.0, 0.0]
 [0.5, 0.15625]
 [0.25, 0.84375]
 [0.75, 0.9375]
 [0.125, 0.4375]
 [0.625, 0.34375]
 [0.375, 0.65625]
 [0.875, 0.5]
 [0.0625, 0.6875]
 [0.5625, 0.59375]
 ⋮
 [0.90625, 0.4375]
 [0.09375, 0.25]
 [0.59375, 0.40625]
 [0.34375, 0.59375]
 [0.84375, 0.6875]
 [0.21875, 0.1875]
 [0.71875, 0.09375]
 [0.46875, 0.90625]
 [0.96875, 0.75]

In [16]:
gen_all_points(C_LP,b)
pts_lp = gen_all_points(C_LP,b)
#pts_lp = sort(gen_all_points(C_LP,b))

32-element Vector{Vector{BigFloat}}:
 [0.0, 0.0]
 [0.5, 0.96875]
 [0.25, 0.9375]
 [0.75, 0.03125]
 [0.125, 0.875]
 [0.625, 0.09375]
 [0.375, 0.0625]
 [0.875, 0.90625]
 [0.0625, 0.75]
 [0.5625, 0.21875]
 ⋮
 [0.90625, 0.40625]
 [0.09375, 0.25]
 [0.59375, 0.71875]
 [0.34375, 0.6875]
 [0.84375, 0.28125]
 [0.21875, 0.625]
 [0.71875, 0.34375]
 [0.46875, 0.3125]
 [0.96875, 0.65625]

In [17]:
pts_unq= unique(pts)
nu_pts_unq=length(pts_unq)
pts_j_unq = unique(pts[j][2] for j in 1:b^m)

16-element Vector{BigFloat}:
 0.0
 0.15625
 0.84375
 0.9375
 0.4375
 0.34375
 0.65625
 0.5
 0.6875
 0.59375
 0.40625
 0.25
 0.75
 0.90625
 0.09375
 0.1875

In [21]:
pts_unq_lp= unique(pts_lp)
nu_pts_unq_lp=length(pts_unq_lp)
pts_j_unq_lp = unique(pts_lp[j][2] for j in 1:b^m)

32-element Vector{BigFloat}:
 0.0
 0.96875
 0.9375
 0.03125
 0.875
 0.09375
 0.0625
 0.90625
 0.75
 0.21875
 ⋮
 0.40625
 0.25
 0.71875
 0.6875
 0.28125
 0.625
 0.34375
 0.3125
 0.65625

In [96]:
# m = 5 Use Ctrl+/ to comment out and back
# w_1 = 0, w_2 =1
# C_cr1 = [1 0 0 0 0; 0 1 0 0 0; 0 0 1 0 0; 0 0 0 1 0; 0 0 0 0 1]
# C_cr2 = [0 0 0 0 1; 0 1 0 0 0; 1 0 0 0 0; 0 0 1 0 0; 0 0 0 0 0]
# C_cr1, C_cr2 = S(C_cr1), S(C_cr2)
# C_cr = [C_cr1,C_cr2]

In [97]:
# w_1 = 1, w_2 = 2
# C_cr1 = [1 1 1 1 0; 0 1 0 1 0; 0 0 1 1 0; 0 0 0 1 0; 0 0 0 0 0]
# C_cr2 = [1 0 0 0 0; 0 1 0 0 0; 0 0 1 0 0; 0 0 0 0 0; 0 0 0 0 0]
# C_cr1, C_cr2 = S(C_cr1), S(C_cr2)
# C_cr = [C_cr1,C_cr2]

In [98]:
#set_theme!(theme_ggplot2())

In [19]:
fig = Figure(resolution = (800, 400))

#kwargs = (; xminorticksvisible = true, xminorgridvisible = true)
#xticks = [0.0, 0.5, 1.0], yticks = [0.0, 0.5, 1.0]
#xminorticks = IntervalsBetween(4), xminorticksvisible = true, ygridvisible = false
#limits = (nothing,nothing, -0.05, 1)

#ax = Axis(fig[1,1], title = "", limits = (nothing,nothing, -0.05, 1))
#scatter!( Point2.(pts) )

ax = Axis(fig[1,1],title = "Hammersley",limits = (nothing,nothing, nothing, 1), xticks = [0.0, 0.25, 0.5, 0.75], yticks = [0.0, 0.25, 0.5, 0.75], xminorgridvisible = false, yminorticksvisible = false)
scatter!( Point2.(pts))

#ax = Axis(fig[1,1], title = "(0,4,2)- net", limits = (nothing,nothing, nothing, 1),  xticks = [0.0, 0.25, 0.5, 0.75], xminorticks = IntervalsBetween(4), xminorticksvisible = true, yticks = [0.0, 0.25, 0.5, 0.75],  xminorgridvisible = true, yminorticksvisible = false, ygridvisible = false)
#scatter!( Point2.(pts_shift) )

ax = Axis(fig[1,2], title = "Upper-1-mat", limits = (nothing,nothing, nothing, 1), xticks = [0.0, 0.25, 0.5, 0.75], yticks = [0.0, 0.25, 0.5, 0.75],xminorgridvisible = false, yminorticksvisible = false)
scatter!( Point2.(pts_lp) )

#ax = Axis(fig[2,1], title = "(2,5,2)-row reduced net, w_2 = 2", limits = (nothing,nothing, nothing, 1), xticks = [0.0, 0.25, 0.5, 0.75], yticks = [0.0, 0.25, 0.5, 0.75],xminorgridvisible = false, yminorticksvisible = false)
#scatter!( Point2.(pts_rr_shift) )

#ax = Axis(fig[2,2], title = "(2,5,2)-row reduced net, w_2 = 3", limits = (nothing,nothing, nothing, 1), xticks = [0.0, 0.5, 1.0], yticks = [0.0, 0.5, 1.0],xminorgridvisible = false, yminorticksvisible = false)
#scatter!( Point2.(pts_rrr_shift) )


#ax = Axis(fig[1,2], title = "(2,4,2)-row reduced net, w_2 = 1", limits = (nothing,nothing, nothing, 1),  xticks = [0.0, 0.25, 0.5, 0.75], xminorticks = IntervalsBetween(2), xminorticksvisible = true, yticks = [0.0, 0.25, 0.5, 0.75],  xminorgridvisible = true, yminorticksvisible = false, ygridvisible = false)
#scatter!( Point2.(pts_cr_shift) )

#ax = Axis(fig[1,3], title = "(2,4,2)-row reduced net, w_2 = 2", limits = (nothing,nothing, nothing, 1),  xticks = [0.0, 0.25, 0.5, 0.75], xminorticks = IntervalsBetween(2), xminorticksvisible = true, yticks = [0.0, 0.25, 0.5, 0.75],  xminorgridvisible = true, yminorticksvisible = false, ygridvisible = false)
#scatter!( Point2.(pts_rr_shift) )

#ax = Axis(fig[1,3], title = "col-row reduced point set")
#scatter!( Point2.(pts_rr) )

#save("Plots/Digital_net_t2_w123_rowred_m5_shift.png", fig)
#save("Plots/Digital_net_t2_w123_rowred_m5_shift.svg", fig)
fig

UndefVarError: UndefVarError: `Figure` not defined

Computing the NRT-weight and Dual space

In [100]:
1+2^5+2^10+2^15

33825

In [101]:
dual_badic = collect(Iterators.product(fill(0:b-1, m*s)...))[:]

256-element Vector{NTuple{8, Int64}}:
 (0, 0, 0, 0, 0, 0, 0, 0)
 (1, 0, 0, 0, 0, 0, 0, 0)
 (0, 1, 0, 0, 0, 0, 0, 0)
 (1, 1, 0, 0, 0, 0, 0, 0)
 (0, 0, 1, 0, 0, 0, 0, 0)
 (1, 0, 1, 0, 0, 0, 0, 0)
 (0, 1, 1, 0, 0, 0, 0, 0)
 (1, 1, 1, 0, 0, 0, 0, 0)
 (0, 0, 0, 1, 0, 0, 0, 0)
 (1, 0, 0, 1, 0, 0, 0, 0)
 ⋮
 (1, 1, 1, 0, 1, 1, 1, 1)
 (0, 0, 0, 1, 1, 1, 1, 1)
 (1, 0, 0, 1, 1, 1, 1, 1)
 (0, 1, 0, 1, 1, 1, 1, 1)
 (1, 1, 0, 1, 1, 1, 1, 1)
 (0, 0, 1, 1, 1, 1, 1, 1)
 (1, 0, 1, 1, 1, 1, 1, 1)
 (0, 1, 1, 1, 1, 1, 1, 1)
 (1, 1, 1, 1, 1, 1, 1, 1)

In [102]:
function nrt_wt(v,b,m,s)
    wt = 0
    for i in 0:m:(m*s -1)
        for j in m:-1:1         #reverse(1:m)
            if v[i+j] != 0
                wt += j
                break
            end
        end
    end
    return wt
end

nrt_wt (generic function with 1 method)

In [103]:
nrt_wt.(dual_badic,b,m,s)

256-element Vector{Int64}:
 0
 1
 2
 2
 3
 3
 3
 3
 4
 4
 ⋮
 7
 8
 8
 8
 8
 8
 8
 8
 8

In [104]:
wt_dict = Dict()
    for x in dual_badic
        wt = nrt_wt(x,b,m,s)
        if haskey(wt_dict,wt)
            push!(wt_dict[wt],x)
        else 
            wt_dict[wt] = [x]
        end
    end 

In [105]:
#Test for m=2
zeros(Int64,1,2) == [0 0]


true

In [106]:
function dual_C(M,b,m,s)
    dual_elt = []
    for n in dual_badic
        if transpose(collect(n))*M == zeros(Int64,1,m)
            dual_elt = push!(dual_elt, n)
        end
    end
    return dual_elt
end

dual_C (generic function with 1 method)

In [107]:
M = [collect(C_1);collect(C_2)]
# transpose(collect(dual_badic[64]))*M == [0 0 0] 

8×4 Matrix{AbstractAlgebra.GFElem{Int64}}:
 1  0  0  0
 0  1  0  0
 0  0  1  0
 0  0  0  1
 0  0  0  1
 0  0  1  0
 0  1  0  0
 1  0  0  0

In [108]:
M_lp = [collect(C_1);collect(C_up)]

8×4 Matrix{AbstractAlgebra.GFElem{Int64}}:
 1  0  0  0
 0  1  0  0
 0  0  1  0
 0  0  0  1
 1  1  1  1
 1  1  1  0
 1  1  0  0
 1  0  0  0

In [109]:
dual_pts = dual_C(M,b,m,s)

16-element Vector{Any}:
 (0, 0, 0, 0, 0, 0, 0, 0)
 (0, 0, 0, 1, 1, 0, 0, 0)
 (0, 0, 1, 0, 0, 1, 0, 0)
 (0, 0, 1, 1, 1, 1, 0, 0)
 (0, 1, 0, 0, 0, 0, 1, 0)
 (0, 1, 0, 1, 1, 0, 1, 0)
 (0, 1, 1, 0, 0, 1, 1, 0)
 (0, 1, 1, 1, 1, 1, 1, 0)
 (1, 0, 0, 0, 0, 0, 0, 1)
 (1, 0, 0, 1, 1, 0, 0, 1)
 (1, 0, 1, 0, 0, 1, 0, 1)
 (1, 0, 1, 1, 1, 1, 0, 1)
 (1, 1, 0, 0, 0, 0, 1, 1)
 (1, 1, 0, 1, 1, 0, 1, 1)
 (1, 1, 1, 0, 0, 1, 1, 1)
 (1, 1, 1, 1, 1, 1, 1, 1)

In [110]:
dual_pts_lp = dual_C(M_lp,b,m,s)

16-element Vector{Any}:
 (0, 0, 0, 0, 0, 0, 0, 0)
 (1, 1, 1, 1, 1, 0, 0, 0)
 (1, 1, 1, 0, 0, 1, 0, 0)
 (0, 0, 0, 1, 1, 1, 0, 0)
 (1, 1, 0, 0, 0, 0, 1, 0)
 (0, 0, 1, 1, 1, 0, 1, 0)
 (0, 0, 1, 0, 0, 1, 1, 0)
 (1, 1, 0, 1, 1, 1, 1, 0)
 (1, 0, 0, 0, 0, 0, 0, 1)
 (0, 1, 1, 1, 1, 0, 0, 1)
 (0, 1, 1, 0, 0, 1, 0, 1)
 (1, 0, 0, 1, 1, 1, 0, 1)
 (0, 1, 0, 0, 0, 0, 1, 1)
 (1, 0, 1, 1, 1, 0, 1, 1)
 (1, 0, 1, 0, 0, 1, 1, 1)
 (0, 1, 0, 1, 1, 1, 1, 1)

In [111]:
nrt_wt.(dual_pts,b,m,s)

16-element Vector{Int64}:
 0
 5
 5
 6
 5
 7
 6
 7
 5
 8
 7
 8
 6
 8
 7
 8

In [112]:
nrt_wt.(dual_pts_lp,b,m,s)

16-element Vector{Int64}:
 0
 5
 5
 6
 5
 7
 6
 7
 5
 8
 7
 8
 6
 8
 7
 8

In [113]:
nrt_wt.(dual_pts,b,m,s) == nrt_wt.(dual_pts_lp,b,m,s)

true

In [114]:
function total_wt(v,b,m,s)
    wt_t = 0
    for i in 0:m:(m*s -1)
        for j in 1:m       
            if v[i+j] != 0
                    wt_t += j
            end
        end
    end
    return wt_t
end

total_wt (generic function with 1 method)

In [115]:
function sumtotal_wt(W)
    wt_total = 0
    for i in 1:length(W)
        wt_total += W[i]
    end
    return wt_total
end

sumtotal_wt (generic function with 1 method)

In [116]:
W_1 = total_wt.(dual_pts,b,m,s)

16-element Vector{Int64}:
  0
  5
  5
 10
  5
 10
 10
 15
  5
 10
 10
 15
 10
 15
 15
 20

In [117]:
println(W_2)

[0, 16, 12, 8, 9, 13, 9, 17, 7, 17, 13, 15, 10, 20, 16, 18, 6, 20, 16, 14, 13, 19, 15, 21, 11, 23, 19, 19, 16, 24, 20, 24]


In [118]:
W_2 = total_wt.(dual_pts_lp,b,m,s)

16-element Vector{Int64}:
  0
 11
  8
  7
  6
 11
  8
 13
  5
 14
 11
 12
  9
 16
 13
 16

In [119]:
sumtotal_wt(W_1)

160

In [120]:
sumtotal_wt(W_2)

160

In [121]:
wt_dict_dual = Dict()
    for x in dual_pts
        wt = nrt_wt(x,b,m,s)
        if haskey(wt_dict_dual,wt)
            push!(wt_dict_dual[wt],x)
        else 
            wt_dict_dual[wt] = [x]
        end
    end 

In [122]:
#wt_dict_dual[8]

In [123]:
wt_dict_dual_lp = Dict()
    for x in dual_pts_lp
        wt = nrt_wt(x,b,m,s)
        if haskey(wt_dict_dual_lp,wt)
            push!(wt_dict_dual_lp[wt],x)
        else 
            wt_dict_dual_lp[wt] = [x]
        end
    end 

In [124]:
#wt_dict_dual_lp[8]